version: "3.7"

services:
  postgres:
    build: postgres
    container_name: "covoting-postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=covoting
    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data
  spring:
    image: b4c7872bf862bc698daa4e59d76f7580f116b548bf224b047c8d21254d915d29
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  frontend:
    build: src/main/frontend
    container_name: "covoting-frontend"
    ports:
      - "80:80"
    depends_on:
      - spring