BEGIN;

CREATE TABLE IF NOT EXISTS public.voting
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1000 ),
    voting_session_id integer NOT NULL,
    seq integer NOT NULL,
    name character varying(200) NOT NULL,
    majority_type character varying(50) NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.voting
    ADD FOREIGN KEY (voting_session_id)
        REFERENCES public.voting_session (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID;

END;