BEGIN;


CREATE TABLE IF NOT EXISTS public.application_user
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1000 ),
    user_type character varying(10) NOT NULL,
    full_name character varying(200) NOT NULL,
    email character varying(100) NOT NULL,
    password_hash character varying(60) NOT NULL,
    vote_weight integer NOT NULL DEFAULT 1,
    PRIMARY KEY (id)
);

END;